easy_admin:
  formats:
    datetime: 'd/m/Y H:i'
  site_name: 'Administrateur'
  list:
    actions: ['show', 'delete']
  show:
    actions: ['-edit']

  entities:
    Projets:
      class: App\Entity\Project
      image_base_path: '%uploads_url%/projects'
      list:
        actions: ['show', '-edit', '-new']
        fields:
          - 'id'
          - 'title'
          - 'city'
          - { property: 'picture', type: 'image' }
          - 'cost'
          - 'excerpt'
          - 'createdAt'
          - 'user'
          - 'comments'
      show:
        fields:
          - 'id'
          - 'title'
          - 'city'
          - 'categories'
          - { property: 'picture', type: 'image' }
          - 'cost'
          - 'excerpt'
          - 'createdAt'
          - 'user'
          - 'comments'
    Categories:
      class: App\Entity\Category
      form:
        fields:
          - 'label'
      show:
        actions: ['edit']
    Commentaires:
      class: App\Entity\Comment
      list:
        actions: ['-new', '-edit']
        fields:
          - 'project'
          - 'title'
          - 'content'
          - 'createdAt'
          - 'user'
    Villes:
      class: App\Entity\City
      image_base_path: '%uploads_url%/cities'
      list:
        fields:
          - 'id'
          - 'name'
          - { property: 'picture', type: 'image' }
          - 'projects'
      form:
        fields:
          - 'name'
          - { property: 'picturePath', label: 'Photo', type: 'file_upload', type_options: { upload_dir: 'public\uploads\cities', upload_delete: "<?php echo '<?php echo 1; ?>'; ?>" }}
      show:
        actions: ['edit']
        fields:
          - 'name'
          - { property: 'picture', type: 'image' }
          - 'projects'
    Utilisateurs:
      class: App\Entity\User
      list:
        actions: ['-new', '-edit']
      show:
        fields:
          - 'email'
          - 'firstname'
          - 'lastname'
          - { property: 'roles', type: 'simple_array' }
          - 'projects'



